### ISSUE TITLE
Scheduled lambda failed to trigger

### ISSUE THREAD

**Issue by antoniuslin** [lambci/docker-lambda#211]
Hello,

I'm not sure if this is a true issue or more of a PEBCAK. I have the following lambda definition in my SAM's `template.yaml`

```
    TestScheduledFunction:
      Type: AWS::Serverless::Function
      Properties:
        Handler: app.test
        Events:
          Promech:
            Type: Api
            Properties:
              Schedule: rate(1 minute)
              Path: /test
              Method: any
```

The function content is a simple `js` function in `app.js`:

```javascript
exports.test = async(event, context, callback) => {
  console.log('triggered call @:', (new Date()).toISOString());
}
```

I'm able to call the lambda just fine via standard `curl` call like so:

```bash
$> curl http://localhost:3000/test
```

as well as using local invocation like so:

```bash
$> sam local invoke TestScheduledFunction --no-event
```

both resulting in similar server-side output like so (with the respective differences):

```
START RequestId: b3ed7724-be8d-1dae-ae54-40478a993fc2 Version: $LATEST
2019-09-26T20:49:05.464Z	b3ed7724-be8d-1dae-ae54-40478a993fc2	INFO	triggered call: 2019-09-26T20:49:05.464Z
END RequestId: b3ed7724-be8d-1dae-ae54-40478a993fc2
```

But the expected scheduled invocation as declared in the `template.yaml` did not trigger. Did I declare it incorrectly? Or is this a bug? Or is it neither because scheduled lambda is not supported in [`SAM local`](https://aws.amazon.com/about-aws/whats-new/2017/08/introducing-aws-sam-local-a-cli-tool-to-test-aws-lambda-functions-locally/)?

Thanks.
