### ISSUE TITLE
Cannot find module 'color'

### ISSUE THREAD

**Issue by screendriver** [lambci/docker-lambda#242]
I'm using [GitHub Actions](https://github.com/features/actions) to run integration tests against your Docker image. Locally on my MacBook everything works fine but when they run in my `GitHub Actions` workflow I get following response:

```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'color'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"
}
```

My `.github/workflows/build.yml` looks like this:

```yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      lambda:
        image: lambci/lambda:nodejs12.x
        ports:
          - 9001:9001
        volumes:
          - $PWD:/var/task:ro,delegated
        env:
          DOCKER_LAMBDA_STAY_OPEN: 1
          AWS_LAMBDA_FUNCTION_HANDLER: lambda/my-test.handler
    steps:
      - ...
```
