### ISSUE TITLE
Debugging documentation

### ISSUE THREAD

**Issue by richarddd** [lambci/docker-lambda#244]
First of all: Thanks for your amazing work on this project!

I understand it is possible to attach a remote debugger to process running in the docker container.

However I'm missing documentation on how to do so?

I'm specifically search for info on how to attach a debugger on *node*, *java* and *python* lambdas when they are running in the container.

Thanks 🙂

**Comment by thetumper** [comment]
An example with node and serverless-offline:

1) Expose the serverless-offline port in your Dockerfile:

EXPOSE 8080

2) And to attach the debugger:
node --inspect="0.0.0.0:${node_debugger_port}" \
  --                                           \
  ./node_modules/.bin/sls offline start        \
  --prefix "${service_uri_prefix}"             \
  --noAuth                                     \
  --host 0.0.0.0                               \
  --port 8080

**Comment by zvictor** [comment]
I was having the same issue and I had to customise the running image to solve it. First I tried using `docker kill --signal SIGUSR1`, as explained [here](https://codefresh.io/docker-tutorial/debug_node_in_docker/), but that didn't work. If anyone knows how to channel `SIGUSR1` into the lambda's node process, please let us know!

**Comment by zvictor** [comment]
**Workaround: start node with `--inspect`**

```Dockerfile
FROM lambci/lambda:nodejs12.x

USER root
RUN sed -i "s/bin\/node/bin\/node --inspect=0.0.0.0:9229/g" /var/runtime/bootstrap
# undo the USER change that was needed above:
USER sbx_user1051
```

The `RUN` command above will change the script that launches your application and will append the [--inspect](https://nodejs.org/en/docs/guides/debugging-getting-started/#enable-inspector) option to have the debugger running at port `9229` of the container. Do not forget to **expose the port `9229`!**

**Comment by zvictor** [comment]
**Workaround 2: replace `/var/runtime/bootstrap` using a volume**

The idea here is to avoid building a custom image.
1. Add the `--inspect` instruction to a copy of the `/var/runtime/bootstrap` file.
2. Add a volume to your running container that replaces the original `/var/runtime/bootstrap` by yours (from step 1).
3. expose the debugging port

For unknown reasons, this solution didn't work that well to me. I managed to get one lambda working well, but a second lambda doesn't start the debugger 🤷‍♀️

**Comment by richarddd** [comment]
I got it working using node by simply setting NODE_OPTIONS and setting the debug port. Then expose that port from my dockerfile :)

BUT, that only solves the "node" debugging, I have no idea how to solve java, c#, python etc .:/

**Comment by zvictor** [comment]
does it work with just `NODE_OPTIONS`? 🤔
I feel so dumb right now... 😆

**Comment by jakub-bochenski** [comment]
If anyone finds this useful setting this env inside the container will allow you to debug Java (checked with jdk11) 
```
JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=127.0.0.1:8000
```

Remember to expose the port too.

**Comment by benze** [comment]
> does it work with just `NODE_OPTIONS`? 🤔
> I feel so dumb right now... 😆

Clearly, I don't know entirely what to do here.  I have tried to set the NODE_OPTIONS environment variable in my docker-compose file but yet the port still remains closed:

```
  lambda:
    image: lambci/lambda:nodejs12.x
    environment: 
      DOCKER_LAMBDA_WATCH: 1
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_DEBUG: 1
      LAMBDA_TASK_ROOT: /var/task/.webpack/service
      NODE_OPTIONS: --inspect=0.0.0.0:9229/g
    command: src/handlers/template.handler
    ports: 
      - "9101:9001"
      - "9229:9229"
    volumes:
      - build_artifacts:/var/task:ro
```


```
$ telnet 192.168.56.99 9229
Trying 192.168.56.99...
telnet: Unable to connect to remote host: Connection refused
```
