### ISSUE TITLE
How to set the time zone？

### ISSUE THREAD

**Issue by goda-kazuki** [lambci/docker-lambda#254]
Hi!

Current dcokcer-compose.yml

```
  getData:
    image: lambci/lambda:nodejs12.x
    tty: true
・
・
・
    ports:
      - 9007:9001
    environment:
      TZ: 'Asia/Tokyo'
    command: index.handler
```

Enter inside the container with docker exec

date command Execute
`Fri Feb 28 09:51:32 JST 2020`
This is the correct time zone

lambda code

```
exports.handler = async (event, context) => {

    console.log(process.env['TZ']);

    const test = new Date();
    console.log(test);
```

process.env['TZ']→Asia/Tokyo
test→2020-02-28T00:51:32.331Z
The time zone of lambda is UTC 

How to set the time zone？
