### ISSUE TITLE
npm install?

### ISSUE THREAD

**Issue by sarink** [lambci/docker-lambda#260]
The readme suggests
```
# To compile native deps in node_modules
docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm rebuild
```
This is fine for compiling the lambda before pushing it.

But, how do I run a local version of my lambda with native dependencies? The function is going to be executed inside the container, so this
```
# Test a `handler` function from an `index.js` file in the current directory on Node.js v12.x
docker run --rm -v "$PWD":/var/task:ro,delegated lambci/lambda:nodejs12.x index.handler
```
is potentially going to fail if I've run the `npm install` from my host (thus defeating the purpose of using this system??). How are we supposed to get the native node modules inside the container during local development?

**Comment by mhart** [comment]
Right, that's why I suggest `npm rebuild` – that should rebuild all native dependencies in your node_modules for a Lambda environment – ie, the same environment that you run in the container. If you then run the function in a container, it will use these native dependencies.

Make sense?

**Comment by sarink** [comment]
Ah, I see, so the workflow is something like
```
# Install new module from host
npm install new-module

# Rebuild dependencies for native
docker run --rm -v "$PWD":/var/task lambci/lambda:build-nodejs12.x npm rebuild

# Run container with new native dependencies
docker run --rm -v "$PWD":/var/task:ro,delegated lambci/lambda:nodejs12.x index.handler
```

**Comment by sarink** [comment]
Is there any way to simplify this? I was trying to do something like
```
# docker-compose.yml
version: '3.7'

services:
  my-lambda:
    image: lambci/lambda:nodejs12.x
    entrypoint: sh
    command: bash -c "npm install && /var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs index.handler"
    volumes:
      - ./my-lambda:/var/task
```
This way, all I have to do is run `docker-compose up my-lambda` every time and it is guaranteed to be correct

However, it feels kind of hacky, and also it doesn't work (fails with `/usr/bin/sh: cannot execute binary file`)

**Comment by mhart** [comment]
Not really sure to be honest – the non-build images aren't intended for anything other than running Lambdas in them. Let us know if you find anything though

**Comment by TimofeyBiryukov** [comment]
@sarink Here is how I managed to do it.
It's dirty, we have to switch user to root, otherwise we get eaccess errors on `npm i`.

```
lambda:
    image: lambci/lambda:nodejs12.x
    entrypoint: sh
    command: /start.sh
    user: root
    ports:
      - 9001:9001
    volumes:
      - ./flow-data-integration/fetch-data-lambda:/var/task
      - ./start.sh:/start.sh
    environment:
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
```

And the `start.sh`:

```bash
#!/bin/bash

cd /var/task
npm i

/var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs index.handler
```
