### ISSUE TITLE
Runtime.ImportModuleError jest

### ISSUE THREAD

**Issue by mattvb91** [lambci/docker-lambda#320]
Im trying to get jest tests running with github actions. Locally it works fine but on github it errors. My github action file looks like this:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: 
      image: lambci/lambda:build-nodejs12.x

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
          curl --silent --location https://rpm.nodesource.com/setup_12.x | bash -
          yum install yarn -y
          for d in $GITHUB_WORKSPACE/lambda/*; do (cd "$d" && yarn --frozen-lockfile); done
          cd $GITHUB_WORKSPACE
          yarn --frozen-lockfile
          yarn build
          ls -la $GITHUB_WORKSPACE/lambda/hooks
          yarn test
    env:
      AWS_DEFAULT_REGION: "us-east-1"

```

```bash
$ tsc
Done in 10.06s.
total 72
drwxr-xr-x  3 root root  4096 Nov 28 11:51 .
drwxr-xr-x  6 root root  4096 Nov 28 11:50 ..
-rw-r--r--  1 root root    11 Nov 28 11:51 hookHandler.d.ts
-rw-r--r--  1 root root  4172 Nov 28 11:51 hookHandler.js
-rw-r--r--  1 root root  1087 Nov 28 11:50 hookHandler.ts
drwxr-xr-x 93 root root  4096 Nov 28 11:51 node_modules
-rw-r--r--  1 root root   281 Nov 28 11:50 package.json
-rw-r--r--  1 root root 40128 Nov 28 11:50 yarn.lock
yarn run v1.22.5
$ jest
FAIL test/lambda.test.ts (18.96 s)
  ✕ Test Empty event results in 500 (8621 ms)

  ● Test Empty event results in 500


    {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'hookHandler'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"}

      3 | 
      4 | test('Test Empty event results in 500', () => {
    > 5 |     var lambdaCallbackResult = dockerLambda({
        |                                ^
      6 |         taskDir: path.resolve(__dirname + "/../lambda/hooks/"),
      7 |         handler: "hookHandler.handler",
      8 |         dockerImage: 'lambci/lambda:nodejs12.x'

      at runSync (node_modules/docker-lambda/index.js:49:13)
      at Object.<anonymous> (test/lambda.test.ts:5:32)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        19.635 s
```

My test code: 

```node
var dockerLambda = require('docker-lambda')
import path from "path"

test('Test Empty event results in 500', () => {
    var lambdaCallbackResult = dockerLambda({
        taskDir: path.resolve(__dirname + "/../lambda/hooks/"),
        handler: "hookHandler.handler",
        dockerImage: 'lambci/lambda:nodejs12.x'
    })

    expect(lambdaCallbackResult.statusCode).toEqual(500);
});
```

Not really sure how to replicate as its working fine locally. I am probably missing some dependancy on the github runner image?
