### ISSUE TITLE
Unable to import module 'lambda_function'

### ISSUE THREAD

**Issue by jasonrhaas** [lambci/docker-lambda#51]
I'm trying to use this docker container to test out a Zappa + Flask deploy and having some issues.  I followed the instructions on the README, and I can't get the Lambda function to run properly.

Is it not importing my Lambda code properly?  What is supposed to happen?

`docker run -v $PWD:/var/task lambci/lambda:python3.6`

```
START RequestId: de56416b-9dfb-4a9f-b5e6-687af6593b61 Version: $LATEST
Unable to import module 'lambda_function': No module named 'flask_restless'
END RequestId: de56416b-9dfb-4a9f-b5e6-687af6593b61
REPORT RequestId: de56416b-9dfb-4a9f-b5e6-687af6593b61 Duration: 7 ms Billed Duration: 100 ms Memory Size: 1536 MB Max Memory Used: 19 MB

{"errorMessage": "Unable to import module 'lambda_function'"}
```

Here is the docker-compose.yml file I am using:

```
version: '3'
services:

  lambda:
    image: lambci/lambda:python3.6
    volumes:
      - $PWD:/var/task
    environment:
      - AWS_LAMBDA_FUNCTION_NAME=application

  mariadb:
    image: mariadb:latest
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/load.sql
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=''
      - MYSQL_USER=''
      - MYSQL_PASSWORD=''
```
