### ISSUE TITLE
CI: Invoking Lambda functions from docker image script

### ISSUE THREAD

**Issue by patoncrispy** [lambci/docker-lambda#8]
I am using GitLab CI to test my code and have been able to make a container that uses your docker image. How do I invoke my functions from a docker image? I haven't quite been able to figure that out. 

This is what I have so far: 

```yml
image: lambci/lambda:build

variables:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: YOUR_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: YOUR_SECRET_ACCESS_KEY

cache:
  paths:
    - node_modules/

stages:
  - build

build_step:
  stage: build
  only:
    - /^feature\/.*$/
    - develop
    - master
  script:
    - npm install
    - npm run lint
    - docker run -v "$PWD":/var/task lambci/lambda
```

When I run this I just get issues finding the docker daemon ('Cannot connect to the Docker daemon. Is the docker daemon running on this host?'). I've also tried using the `docker-lambda` npm package and that gives me similar issues. Is it something I'm doing, or a problem with GitLab CI?

Thanks!
